src/App/App.xaml.cs
src/App/Forms/MainWindow.xaml.cs
src/Models/Models.Constants/App/SettingNames.cs
src/ViewModels/Components/AppViewModel/AppViewModel.cs

允许用户调整窗口高度以浏览更多内容
这个 PR 的目的是什么？
- 功能
固定窗口大小为 500*800
窗口宽度依然不能修改，但是高度可以在不小于400的情况下随意调整
顺便修了最小化后需要二次点击才能唤起应用的问题，并且处理了 BBDown 线程检测异常的情况

适当放宽窗口高度限制

---

.github/release-drafter.yml
src/App/Controls/Base/BiliTransportControls.xaml

这可能是由 `UseLayoutRounding` 属性引起的，但这种像素偏移比较微妙，也可能是图标本身的spacing
这个 PR 的目的是什么？
- Bug 修复
修改一下 release-drafter 的 tag

修复播放图标布局问题

---

src/App/App.csproj
src/Libs/Libs.Adapter/Libs.Adapter.csproj
src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
src/Libs/Libs.Markdown/Libs.Markdown.csproj
src/Libs/Libs.Provider/Libs.Provider.csproj
src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
src/Models/Models.App/Models.App.csproj
src/Models/Models.BiliBili/Models.BiliBili.csproj
src/Models/Models.Constants/Models.Constants.csproj
src/Models/Models.Data/Models.Data.csproj
src/Models/Models.Grpc/Models.Grpc.csproj
src/ViewModels/ViewModels.csproj

玩激进一点，上 .NET8 预览版！
这个 PR 的目的是什么？
- Build 或 CI 更新
依赖相对稳定
芜湖起飞
玩玩

升级至 .net 8

---

src/Models/Models.BiliBili/User/MyInfo.cs

部分新用户尝试登录可能会导致崩溃或者用户信息获取失败，从而无法正常登录
这个 PR 的目的是什么？
- Bug 修复
新用户不能正常登录
修复此问题

修复用户信息获取异常导致的应用崩溃

---

src/Libs/Libs.Adapter/VideoAdapter.cs

添加观看时间戳显示
这个 PR 的目的是什么？
- 功能
历史记录无从获知何时观看
在副标题处新增观看的时间戳

历史记录新增观看时间戳显示

---

src/App/Controls/Base/DynamicItem/DynamicItem.xaml
src/Libs/Libs.Provider/CommunityProvider/CommunityProvider.cs
src/Models/Models.App/Constants/ApiConstants.cs
src/Models/Models.Grpc/bilibili/app/dynamic/v2/dynamic.proto
src/ViewModels/Items/DynamicItemViewModel/DynamicItemViewModel.cs

修复动态不能点赞的问题
这个 PR 的目的是什么？
- Bug 修复
动态不能点赞
修复这个问题

修复动态点赞不生效的问题

---

src/App/Pages/WatchlistPage.xaml.cs
src/ViewModels/Views/WatchlistPageViewModel/WatchlistPageViewModel.Properties.cs
src/ViewModels/Views/WatchlistPageViewModel/WatchlistPageViewModel.cs

这个 PR 的目的是什么？
- 功能
点击清除按钮后无提示直接清空所有（我的稍后再看啊！！！😭）
增加对话框确认清空

清空稍后再看和历史记录时增加对话框

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Handlers.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Methods.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.xaml
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Properties.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

这个 PR 的目的是什么？
- 功能
播放完成后直接关闭播放器
播放完成后弹出 5 秒倒计时

自动关闭播放器前增加倒计时提示

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Handlers.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Methods.cs
src/App/Controls/Danmaku/DanmakuModel.cs
src/App/Controls/Danmaku/DanmakuView/DanmakuView.Methods.cs

修复回退进度时弹幕不显示的问题
这个 PR 的目的是什么？
- Bug 修复
进度回退时，已经发送过的弹幕不会再次显示
移除了原来的检测代码，修复此问题

修复回退进度时弹幕不显示的问题

---

src/Libs/Libs.Adapter/VideoAdapter.cs

移除了 ToLocalTime，该方法会导致额外增加8小时
这个 PR 的目的是什么？
- Bug 修复

修复视频收藏夹的收藏时间不正确的问题

---

src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/ViewModels/Components/AIFeatureViewModel/AIFeatureViewModel.cs

虽然并没有写反，但从这个问题可以看出，现有提示可能会引起误解，所以改为更直接地 `前进`, `后退` 来减少歧义
这个 PR 的目的是什么？
- Bug 修复
提示可能会引起歧义
替换提示
小幻助理进行了更新，优化了协议启动流程，现在在进行AI调用前，不必再要求先启动小幻助理了

更换播放器跳转提示以减少误解

---

src/App/Forms/MainWindow.xaml
src/App/Forms/MainWindow.xaml.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Controls.cs

在写代码的时候忽略了当前是多实例，所以设置的播放速率没有保存。保存之后就 OK 了
这个 PR 的目的是什么？
- Bug 修复
全局播放速率开启后，播放速率没有在下一个视频中生效
修复这个问题

修复全局播放速率不生效的问题

---

src/App/App.csproj
src/App/Controls/AppNavView.xaml
src/App/Controls/AppNavView.xaml.cs
src/App/Converters/NavigateItemTemplateSelector.cs
src/App/Forms/MainWindow.xaml
src/App/Forms/MainWindow.xaml.cs
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/App/Styles/Overwrites.xaml
src/Libs/Libs.Adapter/Libs.Adapter.csproj
src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
src/Libs/Libs.Markdown/Libs.Markdown.csproj
src/Libs/Libs.Provider/Libs.Provider.csproj
src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
src/ViewModels/Components/AppViewModel/AppViewModel.cs
src/ViewModels/Items/NavigateItemViewModel.cs
src/ViewModels/ViewModels.csproj
src/ViewModels/Views/TimelineViewModel/TimelineViewModel.cs

1. 更新引用
2. 添加导航条目头部标识，并改变导航分组顺序
3. 修复动漫时间线初始化失败的问题
这个 PR 的目的是什么？
- 功能
1. 导航条目堆在一起，少了些层次感。
2. 动漫时间线初始化失败
解决这些问题

添加导航条目头部标识

---

src/App/App.csproj

设置 win32 应用图标，以便在任务管理器中增强辨识度
这个 PR 的目的是什么？
- Bug 修复
应用在任务管理器中显示默认图标
使用应用图标

添加 Win32 应用图标

---

src/App/App.csproj
src/App/Controls/Modules/LiveRecommendDetailModule.xaml

修复 UI 错位
这个 PR 的目的是什么？
- Bug 修复

修复直播推荐页面的错误UI

---

src/Libs/Libs.Provider/HttpProvider/HttpProvider.cs
src/Libs/Libs.Provider/LiveProvider/LiveProvider.cs

修复播放直播时因为 Cookie 可能为空，出现的请求异常问题
这个 PR 的目的是什么？
- Bug 修复

修复播放直播时的 Format 问题

---

src/App/Forms/MainWindow.xaml.cs
src/ViewModels/Components/SearchBoxViewModel/SearchBoxViewModel.cs

修复在已经是搜索页面时二次搜索没有工作的问题
这个 PR 的目的是什么？
- Bug 修复

修复重复搜索没有生效的问题

---

src/App/Controls/Base/UserItem/UserItem.xaml

修复显示关注的人及粉丝时，用户头像及用户名无法显示的问题
这个 PR 的目的是什么？
- Bug 修复

修复用户头像及名称显示

---

src/Libs/Libs.Adapter/FavoriteAdapter.cs
src/Libs/Libs.Provider/FavoriteProvider/FavoriteProvider.cs

修复我的收藏里面收藏分类信息不全的Bug，https://github.com/Richasy/Bili.Copilot/issues/228
这个 PR 的目的是什么？
- Bug 修复
https://github.com/Richasy/Bili.Copilot/issues/228
https://github.com/Richasy/Bili.Copilot/issues/179
获取我的收藏多了一个请求

修复收藏夹超过20个后似乎将无法加载 (#228)

---

src/App/Pages/WebDavPage.xaml
src/ViewModels/Views/WebDavPageViewModel/WebDavPageViewModel.cs

修复 WebDAV 刷新按钮不工作的问题
这个 PR 的目的是什么？
- Bug 修复

修复 WebDAV 刷新按钮不工作的问题

---

src/App/Controls/Settings/PlayerModeSettingSection.xaml
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/Models/Models.Constants/App/SettingNames.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Controls.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Video.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs

自动加载上一次播放进度
这个 PR 的目的是什么？
- 功能

默认自动加载上一次播放进度

---

src/App/Controls/Modules/AccountModule.xaml
src/App/Converters/ObjectToVisibilityConverter.cs
src/App/Forms/MainWindow.xaml.cs
src/ViewModels/Components/AccountViewModel/AccountViewModel.Properties.cs
src/ViewModels/Components/AccountViewModel/AccountViewModel.cs
src/ViewModels/Views/MessageDetailViewModel/MessageDetailViewModel.cs

支持显示消息未读提示

---

src/Libs/Libs.WebDavClient/Core/WebDavResource.cs
src/Libs/Libs.WebDavClient/Response/PropfindResponseParser.cs

修复 WebDAV 在没有 displayName 下的替代行为
这个 PR 的目的是什么？
- Bug 修复

修复 WebDAV 解析问题

---

src/App/Controls/Base/ArticleItem/ArticleItem.xaml
src/App/Controls/Modules/FavoritesNavListModule.xaml
src/App/Controls/Modules/FavoritesNavListModule.xaml.cs
src/Libs/Libs.Adapter/FavoriteAdapter.cs
src/Libs/Libs.Provider/CommunityProvider/CommunityProvider.cs
src/Libs/Libs.Provider/FavoriteProvider/FavoriteProvider.cs
src/Libs/Libs.Provider/HttpProvider/HttpProvider.Extension.cs
src/Libs/Libs.Provider/Libs.Provider.csproj
src/Libs/Libs.Provider/PlayerProvider/PlayerProvider.cs
src/Models/Models.App/Constants/ApiConstants.cs
src/Models/Models.BiliBili/Others/VideoFavoriteGalleryResponse.cs
src/Models/Models.BiliBili/Player/FavoriteListResponse.cs
src/Models/Models.BiliBili/Player/VideoPageResponse.cs
src/Models/Models.Data/Video/VideoFavoriteFolder.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
src/ViewModels/Views/VideoFavoriteDetailViewModel/VideoFavoriteDetailViewModel.Properties.cs
src/ViewModels/Views/VideoFavoriteDetailViewModel/VideoFavoriteDetailViewModel.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
src/ViewModels/Views/WebDavPlayerPageViewModel/WebDavPlayerPageViewModel.Methods.cs

可以在收藏夹中查看订阅的视频合集
这个 PR 的目的是什么？
- 功能

收藏夹支持显示视频合集

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Handlers.cs
src/App/Pages/LivePlayerPage.xaml
src/App/Pages/PgcPlayerPage.xaml
src/App/Pages/PgcPlayerPage.xaml.cs
src/App/Pages/VideoPlayerPage.xaml
src/App/Pages/VideoPlayerPage.xaml.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs

修复播放失败后的提醒里没有返回上一级的选项
这个 PR 的目的是什么？
- Bug 修复

修复播放错误时无法返回的问题

---

src/App/Controls/Comment/CommentItem/CommentItem.xaml
src/ViewModels/Items/CommentItemViewModel/CommentItemViewModel.cs

在 VM 中重新刷一下状态.
这个 PR 的目的是什么？
- Bug 修复

修复评论点赞状态错误的问题

---

src/App/App.csproj
src/App/Assets/WebPlayer.js
src/App/Controls/Settings/WebPlayerSettingSection.xaml
src/App/Controls/Settings/WebPlayerSettingSection.xaml.cs
src/App/Forms/MainWindow.xaml.cs
src/App/Pages/SettingsPage.xaml
src/App/Pages/WebPlayerPage.xaml
src/App/Pages/WebPlayerPage.xaml.cs
src/App/Pages/WebSignInPage.xaml.cs
src/App/PlayerUtils.cs
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/App/TraceLogger.cs
src/Libs/Libs.Toolkit/AppToolkit.cs
src/Models/Models.Constants/App/SettingNames.cs
src/Models/Models.Data/Local/PlaySnapshot.cs
src/ViewModels/Components/AppViewModel/AppViewModel.Properties.cs
src/ViewModels/Components/AppViewModel/AppViewModel.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs

Close #225 , Close #218 , Close #215 , Close #174 , Close #138 , Close #131 , Close #130
哈哈哈哈，摆烂了，哈哈哈哈哈，修什么播放问题，直接用网页播放最省事了。啊哈哈哈哈哈哈，焯！🤡🤡
这个 PR 的目的是什么？
- 功能
尝试使用本地播放
直接显示网页播放界面，随便插点js做点自动化就好了

支持使用内建网页视图进行视频播放

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.xaml
src/Libs/Libs.Provider/HomeProvider/HomeProvider.cs

还是需要用客户端的源才比较准确
这个 PR 的目的是什么？
- Bug 修复

修复精选视频的推荐源

---

src/App/Pages/WebPlayerPage.xaml.cs
src/App/Pages/WebSignInPage.xaml.cs
src/Libs/Libs.Provider/AccountProvider/AccountProvider.cs
src/Libs/Libs.Provider/AuthorizeProvider/AuthorizeProvider.Extension.cs
src/ViewModels/Components/NotificationViewModel/NotificationViewModel.cs

会在每次使用网页进行播放/登录时重新刷新 cookie，避免cookie过期
这个 PR 的目的是什么？
- Bug 修复

修复消息 cookie 的刷新问题

---

src/ViewModels/Components/FlyleafPlayerViewModel/FlyleafPlayerViewModel.Methods.cs
src/ViewModels/Components/FlyleafPlayerViewModel/FlyleafPlayerViewModel.Properties.cs
src/ViewModels/Components/FlyleafPlayerViewModel/FlyleafPlayerViewModel.cs
src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.Properties.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
src/ViewModels/IPlayerViewModel.cs
src/ViewModels/Views/LivePlayerPageViewModel/LivePlayerPageViewModel.Methods.cs
src/ViewModels/Views/LivePlayerPageViewModel/LivePlayerPageViewModel.Properties.cs
src/ViewModels/Views/LivePlayerPageViewModel/LivePlayerPageViewModel.cs
src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Properties.cs
src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Properties.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
src/ViewModels/Views/WebDavPlayerPageViewModel/WebDavPlayerPageViewModel.Methods.cs
src/ViewModels/Views/WebDavPlayerPageViewModel/WebDavPlayerPageViewModel.Properties.cs
src/ViewModels/Views/WebDavPlayerPageViewModel/WebDavPlayerPageViewModel.cs

修复 Flyleaf 媒体信息没有正确刷新的问题
这个 PR 的目的是什么？
- Bug 修复

修复媒体信息更新问题

---

src/ViewModels/Components/FlyleafPlayerViewModel/FlyleafPlayerViewModel.cs

需要启动 Audio Filter
这个 PR 的目的是什么？
- Bug 修复

修复 Flyleaf 倍速播放时的异响

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.Handlers.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.cs
src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.xaml
src/App/Forms/MainWindow.xaml.cs
src/App/Forms/PlayerWindow.xaml.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Properties.cs

全屏时显示关闭窗口的按钮
这个 PR 的目的是什么？
- 功能
全屏时不能直接关闭窗口，需要先退出全屏
添加一个自定义按钮以直接关闭窗口
在播放界面底部添加了一个缩略的进度条

全屏时显示关闭窗口按钮

---

src/ViewModels/Components/NotificationViewModel/NotificationViewModel.Properties.cs
src/ViewModels/Components/NotificationViewModel/NotificationViewModel.Tile.cs
src/ViewModels/Components/NotificationViewModel/NotificationViewModel.cs

添加磁贴通知（运行时更新）
这个 PR 的目的是什么？
- 功能

[试验]添加磁贴通知

---

src/App/Controls/Modules/AllDynamicDetailModule.xaml
src/App/Controls/Modules/AllDynamicDetailModule.xaml.cs
src/App/Controls/Modules/LivePartitionDetailModule.xaml.cs
src/App/Controls/Modules/LiveRecommendDetailModule.xaml.cs
src/App/Controls/Modules/PgcRecommendModule.xaml
src/App/Controls/Modules/PgcRecommendModule.xaml.cs
src/App/Pages/ArticlePage.xaml.cs
src/App/Pages/DynamicPage.xaml
src/App/Pages/DynamicPage.xaml.cs
src/App/Pages/PopularPage.xaml.cs
src/ViewModels/Components/InformationFlowViewModel/InformationFlowViewModel.Properties.cs
src/ViewModels/Components/InformationFlowViewModel/InformationFlowViewModel.cs
src/ViewModels/Views/ArticlePageViewModel/ArticlePageViewModel.Properties.cs
src/ViewModels/Views/ArticlePageViewModel/ArticlePageViewModel.cs
src/ViewModels/Views/LivePartitionDetailViewModel/LivePartitionDetailViewModel.Properties.cs
src/ViewModels/Views/LivePartitionDetailViewModel/LivePartitionDetailViewModel.cs
src/ViewModels/Views/PgcRecommendDetailViewModel/PgcRecommendDetailViewModel.Properties.cs
src/ViewModels/Views/PgcRecommendDetailViewModel/PgcRecommendDetailViewModel.cs
src/ViewModels/Views/PopularPageViewModel/PopularPageViewModel.Properties.cs
src/ViewModels/Views/PopularPageViewModel/PopularPageViewModel.cs

修复页面刷新没有滚动到顶部的问题
这个 PR 的目的是什么？
- Bug 修复

修复页面刷新没有滚动到顶部的问题

---

src/Libs/Libs.Adapter/DynamicAdapter.cs

修复综合动态增量加载失败的问题
这个 PR 的目的是什么？
- Bug 修复

修复全部动态增量加载失败的问题

---

src/App/Assets/WebPlayer.js
src/App/Pages/WebPlayerPage.xaml.cs
src/ViewModels/Views/PopularPageViewModel/PopularPageViewModel.cs

1. 关闭网页播放器 DevTool
2. 隐藏网页中的广告元素
3. 修复热门视频中出现的重复条目
这个 PR 的目的是什么？
- Bug 修复

关闭网页播放器 DevTool

---

src/Libs/Libs.Provider/LiveProvider/LiveProvider.cs
src/Models/Models.BiliBili/User/ChatSessionListResponse.cs
src/ViewModels/Components/NotificationViewModel/NotificationViewModel.Tile.cs

修复直播清晰度切换没有正确生效的问题
这个 PR 的目的是什么？
- Bug 修复

修复直播清晰度切换问题

---

src/App/Controls/Settings/WebDavSettingSection.xaml
src/App/Pages/WebDavPage.xaml
src/Models/Models.Constants/App/WebDavFileType.cs
src/ViewModels/Items/WebDavStorageItemViewModel.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.WebDav.cs
src/ViewModels/Views/WebDavPageViewModel/WebDavPageViewModel.cs

1. 修复 WebDAV 刷新后路径丢失的问题
2. 完整显示所有文件，但会禁用不可播放的文件
3. 优化UI
这个 PR 的目的是什么？
- Bug 修复
- 功能

提高 WebDAV 可用性

---

src/Libs/Libs.Adapter/PlayerAdapter.cs
src/Libs/Libs.Provider/PlayerProvider/PlayerProvider.cs
src/Models/Models.BiliBili/Player/SubtitleIndexResponse.cs
src/Models/Models.Data/Player/SubtitleMeta.cs
src/ViewModels/Components/SubtitleModuleViewModel/SubtitleModuleViewModel.cs

修复字幕不显示的问题（网络请求失败）
这个 PR 的目的是什么？
- Bug 修复

修复字幕不显示的问题

---

src/ViewModels/Components/NotificationViewModel/NotificationViewModel.cs

修复动态通知检测时初始化转换动态Id的错误，会导致抛出异常
这个 PR 的目的是什么？
- Bug 修复

修复动态通知初始化问题

---

src/App/Controls/Settings/PlayerControlSettingSection.xaml
src/App/Controls/Settings/WebDavSettingSection.xaml
src/App/Converters/PlayerTypeConverter.cs
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/Models/Models.Constants/Player/PlayerType.cs
src/ViewModels/Components/AppViewModel/AppViewModel.Properties.cs
src/ViewModels/Components/AppViewModel/AppViewModel.cs
src/ViewModels/Items/WebDavStorageItemViewModel.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs
src/ViewModels/Views/WebDavPageViewModel/WebDavPageViewModel.cs

可以利用设备现有的 MPV 播放器播放 WebDAV 中的视频，拥有极高的扩展性
这个 PR 的目的是什么？
- 功能

支持通过外挂 MPV 播放器播放 WebDAV 视频

---

src/ViewModels/Views/SearchDetailViewModel/SearchDetailViewModel.cs

修复搜索页面的侧边栏有时会不显示的问题
这个 PR 的目的是什么？
- Bug 修复

修复搜索侧边栏不显示的问题

---

src/App/Controls/Settings/PlayerControlSettingSection.xaml
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs

修复设置项丢失的问题
这个 PR 的目的是什么？
- Bug 修复

修复播放模式设置缺失的问题

---

src/App/Controls/DebugDialog.xaml.cs
src/Libs/Libs.Adapter/UserAdapter.cs

修复聊天消息列表加载失败的问题
这个 PR 的目的是什么？
- Bug 修复

修复聊天消息列表加载失败的问题

---

src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs

修复 ffmpeg 下关闭自动播放未生效的问题
这个 PR 的目的是什么？
- Bug 修复

修复 ffmpeg 下关闭自动播放未生效的问题

---

src/App/Controls/Base/BiliTransportControls.xaml
src/App/Controls/Settings/PlayerControlSettingSection.xaml
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/Models/Models.Constants/App/SettingNames.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Properties.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs

添加播放速率滑动条开关
这个 PR 的目的是什么？
- 功能

添加播放速率滑动条开关

---

src/Libs/Libs.Provider/AuthorizeProvider/AuthorizeProvider.Extension.cs
src/Models/Models.BiliBili/Authorize/TokenInfo.cs

修复取回授权信息可能会出错的问题

---

src/App/Forms/MainWindow.xaml.cs

调整 mpv 播放窗口弹出方式，使其遵循播放窗口新建设置
这个 PR 的目的是什么？
- Bug 修复

修改 mpv 播放窗口弹出方式

---

src/Models/Models.BiliBili/Core/RecommendCard.cs
src/Models/Models.BiliBili/Search/VideoSearchItem.cs

修复 JSON 解析异常的问题
这个 PR 的目的是什么？
- Bug 修复

修复 JSON 解析异常的问题

---

src/Models/Models.BiliBili/Core/VideoStatusInfo.cs
src/Models/Models.BiliBili/Player/VideoPageResponse.cs
src/Models/Models.BiliBili/User/UserSpaceResponse.cs

这个 PR 的目的是什么？
- Bug 修复 
#401
正常打开aid和cid过长的视频

修复部分aid和cid的int类型越界问题

---

src/App/Controls/Base/BiliPlayerOverlay/BiliPlayerOverlay.xaml

现在在窗口宽度小于720时，视频详情页才会以覆盖的形式弹出
这个 PR 的目的是什么？
- 功能

在更小的宽度下才会触发覆盖式侧页

---

src/Models/Models.BiliBili/Core/Video/ViewLaterVideo.cs
src/Models/Models.BiliBili/Live/LiveAppPlayInformation.cs
src/Models/Models.BiliBili/Pgc/PgcDisplayInformation.cs
src/Models/Models.BiliBili/Pgc/PgcModule.cs
src/Models/Models.BiliBili/Player/InteractionEdgeResponse.cs

新的视频造成了int数值溢出，已经将相关的数据类型换成了 long
这个 PR 的目的是什么？
- Bug 修复

修复稍后在看对于新视频的解析问题

---

src/Libs/Libs.Provider/HomeProvider/HomeProvider.Extension.cs
src/Libs/Libs.Provider/HomeProvider/HomeProvider.cs
src/Models/Models.BiliBili/Partition/SubPartition.cs
src/Models/Models.BiliBili/Pgc/PgcModule.cs

视频子分区可能存在数据溢出，需要调整属性类型。
这个 PR 的目的是什么？
- Bug 修复

修复视频子分区偏移值溢出的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/PlayerNotificationControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPartsSection.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPartSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Events.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

注册事件通知以进行选中项的更新
这个 PR 的目的是什么？
- Bug 修复

修复切换分P选中项没有刷新的问题

---

src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-arm64.pubxml
src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-x64.pubxml
src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

MPV 并不普适，所以将默认播放器调整为原生播放器以避免产生很多相似的初始播放问题
这个 PR 的目的是什么？
重新在打包时包含运行时

默认播放器调整为原生

---

src/Desktop/BiliCopilot.UI/Controls/Components/MomentCardControl/MomentCardControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Moment/MomentImageGallery.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs

给综合动态添加“在浏览器中打开”的选项
这个 PR 的目的是什么？
- 功能

给综合动态添加“在浏览器中打开”的选项

---

src/Desktop/BiliCopilot.UI/ViewModels/View/ViewLaterPageViewModel/ViewLaterPageViewModel.cs

在添加稍后再看视频时检查重复
这个 PR 的目的是什么？
- Bug 修复

修复稍后再看重复视频的问题

---

src/Desktop/BiliCopilot.UI/Controls/Settings/WebDavSettingControl.xaml
src/Desktop/BiliCopilot.UI/Controls/WebDav/WebDavConfigDialog.xaml.cs

直播消息发送应允许为空字符串，具体修复在 bili-kernel 仓库中
这个 PR 的目的是什么？
- Bug 修复

修复直播消息解析失败的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

对于发布时间超过 90 天的视频，使用精确时间
这个 PR 的目的是什么？
- 功能

新的视频发布时间显示

---

src/Desktop/BiliCopilot.UI/App.xaml.cs

点击图标时，如果已经存在应用实例，则尝试激活应用窗口
这个 PR 的目的是什么？
- Bug 修复
Bug 中提到应最大化，但这里除了重新激活窗口外不做额外处理，因为没有找到关于这个行为的明确定义

修复应用窗口激活重定向问题

---

src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/Controls/Player/SubtitlePresenter.xaml
src/Directory.Packages.props

修复多行字幕重叠，并使文本居中显示
这个 PR 的目的是什么？
- Bug 修复

修复多行字幕重叠的问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/MomentCardControl/MomentCardControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

- 在用户空间视频组中增加功能入口
- 在视频播放顶部分享菜单中增加功能入口
这个 PR 的目的是什么？
- 功能

更多添加到稍后再看的功能入口

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/MomentPageViewModel/MomentPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.cs

当用户在动态/用户空间页面中切换了视频/综合区块后，记住选择，下一次默认打开。
这个 PR 的目的是什么？
- 功能

记住上一次选中的动态/用户空间区块

---

src/Desktop/BiliCopilot.UI/Controls/Core/Common/FrameBuffer.cs
src/Directory.Packages.props

引用更新，简化 opengl 渲染代码

---

src/Desktop/BiliCopilot.UI/Controls/Components/LiveCardControl/LiveCardControl.xaml
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionMainHeader.xaml
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionMainHeader.xaml.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePartitionPageViewModel/LivePartitionPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePartitionPageViewModel/LivePartitionPageViewModel.cs

将关注的直播间折叠进顶部入口，同时将 `推荐` 改为 `推荐的直播分区` 以消除歧义
这个 PR 的目的是什么？
- 功能

折叠关注的直播间列表

---

src/Desktop/BiliCopilot.UI/Controls/Core/TransportControl/VideoTransportControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/ArticleReaderPageViewModel/ArticleReaderPageViewModel.cs

在设置/播放器控制中添加播放速率设置项，开启后最高可调6倍速，步幅降至0.1
这个 PR 的目的是什么？
- 功能

增强播放速率调整（最高6倍速，步幅0.1）

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs
src/Libs/Danmaku.Core/DanmakuFrostMaster.cs
src/Libs/Danmaku.Core/DanmakuRender.cs

播放速率作为额外倍率并入弹幕速度计算
这个 PR 的目的是什么？
- Bug 修复

弹幕速度与播放速率同步

---

src/Desktop/BiliCopilot.UI/Controls/Moment/UserSpacePageHeader.xaml
src/Desktop/BiliCopilot.UI/GlobalDependencies.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.cs

用户空间页可以查看用户详情

---

src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
src/Desktop/BiliCopilot.UI/Controls/Components/AppSearchBox.xaml
src/Desktop/BiliCopilot.UI/Controls/Components/AppSearchBox.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/HistoryHeader.xaml
src/Desktop/BiliCopilot.UI/Controls/History/HistoryHeader.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/HistoryPageControlBase.cs
src/Desktop/BiliCopilot.UI/Controls/History/HistoryVideoSearchSection.xaml
src/Desktop/BiliCopilot.UI/Controls/History/HistoryVideoSearchSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/UserSpacePageHeader.xaml
src/Desktop/BiliCopilot.UI/Controls/Moment/UserSpaceVideoSearchSection.xaml
src/Desktop/BiliCopilot.UI/Controls/Moment/UserSpaceVideoSearchSection.xaml.cs
src/Desktop/BiliCopilot.UI/Converters/SearchSuggestRegionIconConverter.cs
src/Desktop/BiliCopilot.UI/Extensions/SearchSuggestTemplateSelector.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/HistoryPage.xaml
src/Desktop/BiliCopilot.UI/Pages/Overlay/UserSpacePage.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Components/SearchBoxViewModel/SearchBoxViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/SearchBoxViewModel/SearchBoxViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/SearchSuggestItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/HistoryPageViewModel/HistoryPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/HistoryPageViewModel/HistoryPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/UserSpacePageViewModel/UserSpacePageViewModel.cs

当位于用户空间页/历史记录页时，顶部搜索框行为变更，可以搜索当前区域的视频：
这个 PR 的目的是什么？
- 功能

支持用户空间/历史记录视频搜索

---

src/Desktop/BiliCopilot.UI/Controls/AI/AIBody.xaml
src/Desktop/BiliCopilot.UI/Controls/Core/Common/RenderControl.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs

给播放器设置了底部的负边距以抵消渲染问题
这个 PR 的目的是什么？
- Bug 修复
顺带处理了一些杂项，包括 AI 模块的初始隐藏以及底部进度条的显隐

修复全屏播放时底部白线

---

src/Desktop/BiliCopilot.UI/Pages/Overlay/WebDavPlayerPage.xaml

Visual State 没有及时更新
这个 PR 的目的是什么？
- Bug 修复

修复 WebDAV 在全窗口/全屏下没有撑满容器的问题

---

src/Desktop/BiliCopilot.UI.Models/Constants/PlayerDisplayMode.cs
src/Desktop/BiliCopilot.UI/Converters/DisplayModeConverter.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Items/EpisodeItemViewModel/EpisodeItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/SeasonItemViewModel/SeasonItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs

在 `默认播放器显示模式` 中新增 `新窗口` 选项
选择该选项后，视频/直播/动漫/电影等媒体内容会默认在新窗口中打开
这个 PR 的目的是什么？
- 功能

支持默认以新窗口打开视频

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/DownloadSettingControl.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

支持在下载设置中调整是否跳过 AI 字幕下载（默认开启）。
关闭后，将允许下载AI生成的字幕
这个 PR 的目的是什么？
- 功能

支持配置是否跳过 AI 字幕下载

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs

修复播放控制器在鼠标移除播放器时没有隐藏的问题
这个 PR 的目的是什么？
- Bug 修复

修复播放控制器在鼠标移除播放器时没有隐藏的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/View/PopularPageViewModel/PopularPageViewModel.Requests.cs

移除咨资讯区排行榜，因为该分区没有排行榜
这个 PR 的目的是什么？
- Bug 修复

移除资讯分区排行榜（因为不存在）

---

src/Desktop/BiliCopilot.UI/Controls/Components/VideoCardControl/VideoCardControl.xaml

添加一个 icon 以进行区分
这个 PR 的目的是什么？
- Bug 修复

调整推荐视频的标签显示

---

src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw

页面上添加 InfoBar 提示，引导用户查看AI配置说明
这个 PR 的目的是什么？
- 功能

AI 页面添加配置提示

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Directory.Packages.props

对于在 AMD 平台尝试使用内置 mpv 播放器的用户进行不兼容提醒

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

待我学完shader，回来重写
这个 PR 的目的是什么？
- Bug 修复

修复原生播放器下弹幕加载导致线程阻塞的问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml
src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml.cs

修复评论详情中的溢出内容没有更新的问题
这个 PR 的目的是什么？
- Bug 修复

修复评论详情溢出文本未更新的问题

---

src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/Controls/Core/Common/ISwapChainPanelNative.cs

来自 @hez2010 的提醒，在 csproj 中打开 BuiltInComInteropSupport 会影响剪裁，正确做法应该是使用 GeneratedComInterface
这个 PR 的目的是什么？

使用 GeneratedComInterface 来生成 COM 接口

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/ExternalPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/PlayerResources.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
src/Libs/Danmaku.Core/DanmakuFrostMaster.cs

使用外部播放器时，弹幕异常且日志数据绑定失效，这个 PR 用来修复它
这个 PR 的目的是什么？
- Bug 修复

修复外部播放器的绑定问题

---

src/Desktop/BiliCopilot.UI/Toolkits/FileToolkit.cs

File API 不能判断 ，ms-local 路径，导致永远无法读取 config 文件
这个 PR 的目的是什么？
- Bug 修复

修复 webdav 配置没有正确读取的问题

---

src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs

调整UI优先级
这个 PR 的目的是什么？
- Bug 修复

修复进入播放独占模式时的卡顿问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/NotifyMessageCardControl/NotifyMessageCardControl.xaml

没有给控件命名，屮
这个 PR 的目的是什么？
- Bug 修复

修复通知消息条目跳转问题

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
src/Desktop/BiliCopilot.UI/Controls/Components/TopNavigationItem.xaml
src/Desktop/BiliCopilot.UI/Controls/Components/TopNavigationItem.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/LayoutSettingSection.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/LayoutSettingSection.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

支持显示顶部导航（收藏/稍后再看/观看历史的快捷入口）

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs

使弹幕组件不完全覆盖视频区域即可
这个 PR 的目的是什么？
- Bug 修复

修复视频画面因弹幕而消失的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

修复高清（1080）选择顺序

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/LivePlayerPage.xaml
src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml
src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml

更换监听大小改变的元素
这个 PR 的目的是什么？
- Bug 修复

修复仅窗口高度变化时播放器大小没有更新的问题

---

README.md
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw

这个 PR 的目的是什么？
- 其他，请描述内容：修正文案
此 PR 将应用与 README 中的 *哔哩助理和**哔哩助理**采用同样的AI配置* 修正为 *哔哩助理和**小幻助理** [中文名称参考 [Richasy/Rodel.Agent/README.zh-CN.md](https://github.com/Richasy/Rodel.Agent/blob/main/README.zh-CN.md)] 采用同样的 AI 配置*，并依据惯例在中英文之间加入了空格。
抱歉我正在尝试入门 C#，暂时没有深入维护应用组件的能力，thanks for reviewing & merging this minor change！ :)

修正哔哩助理 AI 能力文案

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs

在主页切换时也检查顶部导航状态
这个 PR 的目的是什么？
- Bug 修复

修复顶部导航在切换主页面时依然选中的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Libs/Danmaku.Core/Logger.cs

win2d 和 swapchain 重叠时经常出现绘制失灵的问题
这个 PR 的目的是什么？
- Bug 修复

[临时] 修复弹幕重绘后消失的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.Win32.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/IFullScreenToggleWindow.cs
src/Desktop/BiliCopilot.UI/Forms/MainWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/AppViewModel/AppViewModel.cs

在进入全窗口/小窗模式时显示标题栏，并显示当前正在播放的视频标题
这个 PR 的目的是什么？
- 功能

进入全窗口/小窗模式时显示标题栏

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
src/Libs/Danmaku.Core/DanmakuRender.cs

关闭全局播放速率后重置速率为1
这个 PR 的目的是什么？
- Bug 修复

关闭全局播放速率后重置速率为1

---

src/Desktop/BiliCopilot.UI.Models/Constants/MTCBehavior.cs
src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
src/Desktop/BiliCopilot.UI/Controls/AI/AIFooter.xaml
src/Desktop/BiliCopilot.UI/Controls/AI/AIHeader.xaml
src/Desktop/BiliCopilot.UI/Controls/AI/AIOverlayPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/AI/AIPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/AI/AIPanel.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerMainHeader.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

为了适应island player做出的调整
这个 PR 的目的是什么？
- 功能

播放视频时，AI面板改作弹出层

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
src/Desktop/BiliCopilot.UI/Converters/MTCBehaviorConverter.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw

在播放器控制中新增选项，支持用户自行设置如何弹出播放控制器
这个 PR 的目的是什么？
- 功能

支持播放控制器弹出方式设置

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/AIResponseSettingControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/AIResponseSettingControl.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Package.appxmanifest
src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/AIViewModel/AIViewModel.Chat.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/EpisodeItemViewModel/EpisodeItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/SeasonItemViewModel/SeasonItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

支持以非流式请求 AI 服务，以避免因部分第三方服务不支持流式响应而导致无法使用的问题
这个 PR 的目的是什么？
- 功能

支持调整 AI 响应类型（全文或流式）

---

nuget.config
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Libs/Danmaku.Core/Danmaku.Core.csproj

据说 .NET 9 nightly build 修复了 WinRT XAML 随机崩溃的问题，所以切换到 .NET 9 构建项目
这个 PR 的目的是什么？

切换到 .NET9 构建

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs

修复弹幕渲染问题
这个 PR 的目的是什么？
- Bug 修复

设置弹幕边距，避免渲染问题

---

src/Desktop/BiliCopilot.UI.Models/Constants/PreferDecodeType.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
src/Desktop/BiliCopilot.UI/Converters/PreferDecodeTypeConverter.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

直接使用 gpu-next 虽然可以播杜比，但CPU占用较高，所以初始值改成了自动，以缓解部分设备的压力，并支持手动调整（gpu-next 相当于 vulkan 解码）
这个 PR 的目的是什么？
- 功能

支持针对岛播放器调整硬解类型

---

src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPlaylistSectionDetailViewModel.cs

没有注入 Page 视图模型导致的问题
这个 PR 的目的是什么？
- Bug 修复

修复播放列表无法点击切换的问题

---

src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs

在进入播放独占模式时，在标题栏上显示返回按钮

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.xaml

修复 PGC 可能因为分辨率为空导致请求失败的问题
这个 PR 的目的是什么？
- Bug 修复

修复 PGC 分集请求失败的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs

加一个延时操作
这个 PR 的目的是什么？
- Bug 修复

修复岛播放器全局速率可能不成功的问题

---

src/Desktop/BiliCopilot.UI/Controls/Settings/ModelClientEndpointConfigSettingSection.xaml.cs

修复 Ollama 终结点没有正确显示的问题

---

Bili.Copilot.sln
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-arm64.pubxml
src/Desktop/BiliCopilot.UI/Properties/PublishProfiles/win-x64.pubxml
src/Directory.Build.props
src/Libs/Beta/BiliAgent.Core/BiliAgent.Core.csproj
src/Libs/Beta/BiliAgent.Core/Providers/AzureOpenAIProvider.cs
src/Libs/Beta/Connectors.WebDav/Connectors.WebDav.csproj

莫名其妙在关闭 AOT 的时候，semantic-kernel 还是关闭了 json 反序列化反射
这个 PR 的目的是什么？
- Bug 修复

修复 AI 关闭 json 反射的问题

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/LiveDanmakuPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml

Win2D 的渲染有时候会莫名其妙地中断，这个 PR 只能降低复现概率，如果仍出现没有弹幕的情况，可以再开关一次
这个 PR 的目的是什么？
- Bug 修复

降低切换弹幕可见性后的弹幕消失概率

---

src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs

除 Vulkan 外，将 gpu-context 默认选择为 win，以提高在 Windows 桌面平台的渲染能力
这个 PR 的目的是什么？
- Bug 修复

优化岛播放器的 GPU 播放表现

---

src/Desktop/BiliCopilot.UI/Converters/PlayerTypeConverter.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

内置的 MPV 已经可以被岛播放器取代了
这个 PR 的目的是什么？

移除 MPV 播放器选项

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs

部分设备对 gpu-context 为 win 的效果不佳，会黑屏，所以将自动配置改为 auto
这个 PR 的目的是什么？
- Bug 修复

修复部分设备在偏好解码为自动时黑屏的问题

---

src/Libs/Beta/BiliAgent.Core/Providers/GeminiProvider.cs

修复 Gemini 的请求问题，因为传入的安全设置有误（可能是服务端更新了）
这个 PR 的目的是什么？
- Bug 修复

修复 Gemini 请求失败的问题

---

src/Desktop/BiliCopilot.UI.Models/Constants/PreferDecodeType.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
src/Desktop/BiliCopilot.UI/Converters/PreferDecodeTypeConverter.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

可以自定义岛（MPV）播放器配置，以便部分高级用户自定义播放体验
这个 PR 的目的是什么？
- 功能

支持自定义MPV配置文件

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs

1. 修复弹幕输入时按下空格键会暂停的问题
2. 修复输入时可能会隐藏播放控制器的问题
这个 PR 的目的是什么？
- Bug 修复

修复弹幕输入组件相关的问题

---

src/Desktop/BiliCopilot.UI/Controls/Comment/CommentMainPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/Components/CommentItemControl/CommentItemControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/CommentMainViewModel/CommentMainViewModel.cs

修复置顶评论没有正确显示的问题
这个 PR 的目的是什么？
- Bug 修复

修复置顶评论没有显示问题

---

src/Desktop/BiliCopilot.UI/Controls/Player/LiveInfoSection.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/UpSectionControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/VideoDescriptorControl.xaml

简化关注按钮文本，并在UP名过长时自动裁切
这个 PR 的目的是什么？
- Bug 修复

修复关注按钮被截断的问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/MomentCardControl/MomentCardControl.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/MomentItemViewModel/MomentItemViewModel.cs

在视频动态里显示动态时长
这个 PR 的目的是什么？
- 功能

在视频动态中显示视频时长

---

src/Desktop/BiliCopilot.UI/Controls/AI/AIBody.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/AIViewModel/AIViewModel.Chat.cs
src/Libs/Beta/BiliAgent.Core/AgentClient.cs

在 AI 发生错误时，直接在界面上显示错误信息
这个 PR 的目的是什么？
- 功能

完善 AI 错误提示

---

src/Desktop/BiliCopilot.UI/Controls/Article/ArticlePartitionMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Comment/CommentDetailPanel.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Comment/CommentMainPanel.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Favorites/PgcFavoriteBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Favorites/UgcFavoriteBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Favorites/VideoFavoriteBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/ArticleHistorySection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/HistoryVideoSearchSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/LiveHistorySection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/History/VideoHistorySection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LiveRecommendMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LiveSubPartitionMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Message/MessagePageSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Message/NotifyMessageBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/ComprehensiveMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/ComprehensiveMomentSpaceControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/UserSpaceVideoSearchSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/VideoMomentSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/VideoMomentSpaceControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Pgc/EntertainmentIndexMainControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Popular/PopularMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/ArticleSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/LiveSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/PgcSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/UserSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/VideoSectionDetailControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Users/FansBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Users/FollowsMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/VideoPartition/VideoPartitionMainBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/ViewLater/ViewLaterBody.xaml.cs

不再滚动到底部才触发增量加载，而是在接近最后一行内容时就开始增量加载
这个 PR 的目的是什么？
- Bug 修复

调整增量加载的触发时机

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs

在主页重复导航时检查顶部标签的选中状态
这个 PR 的目的是什么？
- Bug 修复

修复顶部导航的选中问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs

支持长按左键倍速播放

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/MainWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/SubtitleViewModel.cs

支持长按右键加速播放。同时修复键鼠模式下，长按鼠标右键没有加速播放的问题
这个 PR 的目的是什么？
- Bug 修复
- 功能

支持长按右键三倍速播放

---

src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw

修改播放器类型设置描述，AMD 现可正常使用岛播放器

---

src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs

修复小窗播放时的标题栏拖拽问题

---

src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Components/AccountViewModel/AccountViewModel.cs

如果用户因修改密码导致登录失败，应提供可以重新登录的入口点
这个 PR 的目的是什么？
- Bug 修复

当自动登录失败时弹出警告

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/ExternalPlayerViewModel/ExternalPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

原生播放器重置进度后还需要强制播放一下
这个 PR 的目的是什么？
- Bug 修复

修复原生播放器循环播放未生效的问题

---

Bili.Copilot.sln
src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Directory.Packages.props
src/Libs/Beta/BiliAgent.Core/Providers/AzureOpenAIProvider.cs
src/Libs/Danmaku.Core/Danmaku.Core.csproj

.NET / WinAppSDK 版本常规升级
这个 PR 的目的是什么？
- Build 或 CI 更新

更新到 .NET 9 / WinAppSDK 1.6.241106002

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/SubtitleViewModel.cs

存储字幕的数组应该在清除时重置
这个 PR 的目的是什么？
- Bug 修复

修复分集字幕未更新的问题

---

src/Directory.Packages.props

希望别再被背刺了
这个 PR 的目的是什么？
- Build 或 CI 更新

更新到 Windows App SDK 1.6.3

---

src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoSearchSectionDetailViewModel/VideoSearchSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SearchPageViewModel/SearchPageViewModel.cs

目前没有足够的时间来去逆向API变更，所以暂时将默认的视频搜索结果排序方式调整为 `最多播放`
这个 PR 的目的是什么？
- Bug 修复
啧……唉……

临时处理搜索结果为空的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Danmaku/DanmakuBox.xaml
src/Desktop/BiliCopilot.UI/Controls/Danmaku/DanmakuBox.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/PgcPlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/Overlay/VideoPlayerPage.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs

原因是和播放控制器自动显隐逻辑冲突
这个 PR 的目的是什么？
- Bug 修复

修复弹幕输入框聚焦问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/VideoCardControl/VideoCardControl.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoSearchSectionDetailViewModel/VideoSearchSectionDetailViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoSearchSectionDetailViewModel/VideoSearchSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SearchPageViewModel/SearchPageViewModel.cs

将视频搜索实现从 grpc 替换为网页 API，用以修复这个问题
这个 PR 的目的是什么？
- Bug 修复

修复综合搜索结果为空的问题

---

src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj.user
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/NavigationSettingControl.xaml
src/Desktop/BiliCopilot.UI/Controls/Settings/NavigationSettingControl.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/SettingsPage.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/NavigationViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

可以在设置里开启或隐藏导航条目
这个 PR 的目的是什么？
- 功能

支持设置单个导航条目的可见性

---

src/Desktop/BiliCopilot.UI/GlobalDependencies.cs

忘了添加全局内核
这个 PR 的目的是什么？
- Bug 修复

修复 AOT 下 AI 功能不能使用的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Events.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs

在刚开始播放时就把属性设置好，而不是在播放后再附加属性
这个 PR 的目的是什么？
顺便把badge删了，没啥用

优化mpv播放初始化参数配置

---

src/Desktop/BiliCopilot.UI/Controls/Article/ArticlePartitionSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Components/AppSearchBox.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Components/EmotePanel.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Favorites/FavoritesPageSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionMainSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/LivePartition/LivePartitionSubSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Message/MessagePageSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Moment/ComprehensiveSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Pgc/AnimeTimelineSideControl.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/LiveChatSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/LivePlayerFormatButton.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/PgcEpisodesSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/PgcPlayerFormatButton.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/PgcSeasonsSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/SubtitleButton.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPartsSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlayerFormatButton.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlaylistSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Popular/PopularSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Search/SearchSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Users/FollowsSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/VideoPartition/VideoPartitionSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/WebDav/WebDavPlayerSideBody.xaml.cs
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Pages/GalleryPage.xaml.cs
src/Directory.Packages.props

合集未加载时滚动会阻塞UI导致崩溃
这个 PR 的目的是什么？
- Bug 修复
顺便处理之前没处理完的 ItemsView 数据源重置逻辑

修复部分视频播放崩溃的问题
