src/App/Controls/Base/UserItem/UserItem.xaml
src/Models/Models.BiliBili/User/UserSpaceResponse.cs

修复用户数据解析的问题，原因是一个没有使用的属性 `next_exp` 类型错误（对于LV6用户，该属性为字符串，低于LV6的永福，该属性为 int）
这个 PR 的目的是什么？
- Bug 修复
LV6以下的用户无法打开用户空间
修复这个问题
顺便给用户卡片的头像添加了显示详情的命令

修复用户信息解析问题

---

src/App/Controls/Modules/LiveInformationView.xaml
src/App/Controls/Modules/PgcInformationView.xaml
src/App/Controls/Modules/VideoInformationView.xaml

修复描述文本不可选的问题
这个 PR 的目的是什么？
- Bug 修复
视频播放详情中的描述文本不可选择
文本可选

修复播放详情的描述文本不可选的问题

---

src/App/App.xaml.cs

修复最大化时窗口高度超出范围的问题
这个 PR 的目的是什么？
- Bug 修复
点击最大化按钮后，窗口的高度与屏幕高度一致，导致底部被任务栏遮挡
修复这个问题，限制了窗口的最大高度

修复最大化时的窗口高度

---

src/App/Forms/PlayerWindow.xaml.cs
src/Models/Models.Constants/App/SettingNames.cs

支持记录上一次播放窗口关闭时的宽高，并在下一次打开时恢复
这个 PR 的目的是什么？
- 功能
播放器窗口每次都会以1280*720的大小打开
记录上一次窗口关闭时的宽高

支持播放窗口大小记忆

---

src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs

修复循环播放时的起点不在原点的问题
这个 PR 的目的是什么？
- Bug 修复
循环播放时，播放起点可能不在原点
修复此问题

修复循环播放起始点异常的问题

---

src/Libs/Libs.Toolkit/AppToolkit.cs
src/ViewModels/Views/VideoFavoriteDetailViewModel/VideoFavoriteDetailViewModel.cs

78. HexToColor 方法未正确处理发送弹幕时传入的 16 进制颜色编码
80. 有时会重复获取第一页的数据，且未做判断直接加入列表
- Bug 修复
78. 直接使用 Convert.ToInt32 转换字符串导致异常
80. 获取下一页数据后，在加入列表前判断是否已存在
78. 使用 TryParse 转换并判断，转换失败默认为是 合法的 无需转换的 颜色编码
80. 未探究为何会重复获取第一页，仅做了 Any 判断
**由于不熟悉 PR 操作，所以在此条未通过的情况下又做了提交，不得不重新编辑此条信息，下不为例**

1. HexToColor 方法未正确处理 16 进制颜色编码，2. 收藏夹重复加载第一页

---

src/ViewModels/Views/VideoFavoriteDetailViewModel/VideoFavoriteDetailViewModel.cs

这个 PR 的目的是什么？
- Bug 修复
加载收藏夹列表时，用户的默认收藏夹固定加入 Folders
默认收藏夹改为加入 folderList 变量，再通过后续流程去重添加
**此问题好像是 GetDataAsync 和 SelectFolderAsync 两个方法间有循环调用，可能与收藏夹列表下拉框的选择后事件有关。**
**奈何本人初次接触基于 XAML 的项目，能力实在有限，只能用最笨的方法处理此问题。😂**

收藏列表刷新时默认收藏夹重复的问题

---

src/App/Controls/Modules/VideoFavoriteModule.xaml
src/Models/Models.Data/Video/VideoFavoriteFolder.cs

这个 PR 的目的是什么？
- 功能
收藏夹列表只有标题
收藏夹列表标题后增加视频数量

收藏夹列表的标题中增加总数

---

src/App/Controls/Modules/VideoFavoriteModule.xaml
src/App/Forms/PlayerWindow.xaml.cs
src/App/TraceLogger.cs

采集播放器类型数据，以此判断用户对 Native 和 ffmpeg 的倾向
这个 PR 的目的是什么？
没有采集播放器类型数据
采集播放器类型数据
顺便修改了一下收藏夹选择项的UI，使视频数居中显示

添加播放器类型数据采集

---

src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Views/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
src/ViewModels/Views/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

修复当视频播放结束后，会在不启用连续播放的情况下弹出播放下一视频的提示
这个 PR 的目的是什么？
- Bug 修复
视频播放结束后，即便没有下一个要播放的视频也会弹出提示
修复这个问题

修复跳转视频提示不正常弹出的问题

---

src/App/Controls/AppTitleBar.xaml.cs
src/App/Forms/MainWindow.xaml.cs
src/App/Forms/WindowBase.cs

修复标题栏返回按钮的交互区域总是少一块的问题
这个 PR 的目的是什么？
- Bug 修复
当尝试点击返回按钮时，总是在左侧中间区域有一部分不可交互，很容易误触发系统菜单
禁用了默认的系统菜单选项，修复了这个问题

修复标题栏返回按钮交互区域受限的问题

---

src/Libs/Libs.Adapter/LiveAdapter.cs
src/Libs/Libs.Adapter/PlayerAdapter.cs
src/Models/Models.Data/Live/LiveMediaInformation.cs
src/Models/Models.Data/Live/LivePlaylineInformation.cs
src/Models/Models.Data/Player/MediaInformation.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Video.cs

当开启选项时，将所有 P2P CDN 的链接都替换成普通 CDN
这个 PR 的目的是什么？
- Bug 修复
开启 P2P CDN 屏蔽后，没有匹配到正确的 P2P CDN 链接
修复这个问题

修复去除 P2P CDN 没有生效的问题

---

src/App/Controls/Base/VideoItem/VideoItem.xaml
src/App/Controls/Modules/HistoryModule.xaml
src/App/Controls/Modules/VideoFavoriteModule.xaml
src/App/Controls/Modules/VideoInformationView.xaml
src/App/Controls/Modules/VideoInformationView.xaml.cs
src/App/Controls/Modules/ViewLaterModule.xaml
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
src/ViewModels/Views/VideoFavoriteDetailViewModel/VideoFavoriteDetailViewModel.cs

支持在视频条目右键菜单和视频播放信息中复制视频的播放网址
这个 PR 的目的是什么？
- 功能
不支持复制视频网址
支持

支持一键复制视频播放地址

---

src/App/Controls/Base/CardPanel/CardPanel.xaml

修复卡片字色发灰的问题
这个 PR 的目的是什么？
- Bug 修复
卡片字色初始为 TextFillColorSecondaryBrush
现改为 TextFillColorPrimaryBrush

修复卡片字色发灰的问题

---

src/App/Controls/Modules/FilmNavListModule.xaml
src/App/Controls/Modules/LivePartitionDetailModule.xaml.cs
src/App/Controls/Modules/PgcRecommendModule.xaml.cs
src/ViewModels/Views/LivePartitionDetailViewModel/LivePartitionDetailViewModel.cs
src/ViewModels/Views/PgcRecommendDetailViewModel/PgcRecommendDetailViewModel.Properties.cs
src/ViewModels/Views/PgcRecommendDetailViewModel/PgcRecommendDetailViewModel.cs
src/ViewModels/Views/VideoPartitionDetailViewModel/VideoPartitionDetailViewModel.Properties.cs
src/ViewModels/Views/VideoPartitionDetailViewModel/VideoPartitionDetailViewModel.cs

修复影视没有正确根据索引筛选条件排序的问题
这个 PR 的目的是什么？
- Bug 修复
影视页面，无法通过索引筛选条件排序
修复这个问题
顺带修复PGC索引页面切换条件后没有重置滚动位置的问题，以及直播没有重置滚动问题

修复影视索引排序问题

---

src/App/Controls/Modules/AnimeNavListModule.xaml
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs

修复全局播放速率会影响直播的问题
这个 PR 的目的是什么？
- Bug 修复
开启全局播放速率后，在视频播放中设置的播放速率会同步到直播
直播时，播放速率强制设置为1

修复全局播放速率会影响直播的问题

---

src/App/Forms/MainWindow.xaml.cs

在主窗口播放视频后，如果直接关闭应用，再从任务栏重新唤醒，会显示一片空白。这是因为 OverlayFrame 没有关闭的原因
这个 PR 的目的是什么？
- Bug 修复

修复重新唤醒应用后空白的问题

---

src/App/Controls/Base/ArticleItem/ArticleItem.xaml
src/App/Forms/MainWindow.xaml.cs
src/Libs/Libs.Adapter/VideoAdapter.cs
src/Libs/Libs.Provider/PlayerProvider/PlayerProvider.cs
src/Models/Models.BiliBili/Player/SubtitleIndexResponse.cs
src/Models/Models.BiliBili/Player/VideoPageResponse.cs
src/Models/Models.Data/Video/VideoPlayerView.cs
src/Models/Models.Grpc/bilibili/app/view/v1/view.proto

修复手段比较脏，那些不显示的合集只会在网页 API 中出现。目前来看，网页 API 和 APP Api 互有信息缺失，当前只能综合两者进行判断。所以每次都会发送两个请求（无所谓了，摆烂）
这个 PR 的目的是什么？
- Bug 修复
部分视频合集无法显示
修复这个问题

修复部分用户合集不显示的问题

---

src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs

当主窗口播放时，播放完成自动关闭将会选择关闭播放器而不是关闭窗口
这个 PR 的目的是什么？
- Bug 修复

修复主窗口播放时的自动结束逻辑问题

---

src/App/Controls/AppContentDialog.cs
src/App/Controls/CloseWindowTipDialog.xaml
src/App/Controls/CloseWindowTipDialog.xaml.cs
src/App/Controls/DebugDialog.xaml
src/App/Controls/DebugDialog.xaml.cs
src/App/Controls/Settings/MpvSettingSection.xaml.cs
src/App/Controls/TipDialog.xaml
src/App/Controls/TipDialog.xaml.cs
src/App/Controls/UpdateDialog.xaml
src/App/Controls/UpdateDialog.xaml.cs
src/App/Controls/WebDavConfigDialog.xaml
src/App/Controls/WebDavConfigDialog.xaml.cs
src/App/Forms/MainWindow.xaml.cs
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/Libs/Libs.Provider/AuthorizeProvider/AuthorizeProvider.Extension.cs
src/Libs/Libs.Toolkit/AppToolkit.cs
src/ViewModels/Components/AppViewModel/AppViewModel.Properties.cs

MPV 安装脚本依赖 PowerShell，这一点没有很好地提示用户，导致出现一些点击下载按钮无响应的 bug。
现在会在用户设备上没有安装 PowerShell 时给出提示
这个 PR 的目的是什么？
- Bug 修复

修复 MPV 下载提示不完全的问题

---

src/App/Controls/Base/BiliTransportControls.xaml
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Properties.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.cs

在多P下，切换分P会导致当前播放资源释放，这会重置播放速率选项，但实际上这是不必要的。
这个 PR 的目的是什么？
- Bug 修复

修复在多 P 视频下，倍速选项会消失的问题

---

src/App/Controls/Settings/PlayerControlSettingSection.xaml
src/App/Resources/zh-Hans/Resources.resw
src/App/Resources/zh-Hant/Resources.resw
src/Libs/Libs.Adapter/Libs.Adapter.csproj
src/Libs/Libs.Flyleaf/Libs.Flyleaf.csproj
src/Libs/Libs.Provider/HttpProvider/HttpProvider.cs
src/Libs/Libs.Provider/Libs.Provider.csproj
src/Libs/Libs.Provider/PlayerProvider/PlayerProvider.cs
src/Libs/Libs.ResourceGenerator/Libs.ResourceGenerator.csproj
src/Libs/Libs.Toolkit/Libs.Toolkit.csproj
src/Models/Models.Constants/App/SettingNames.cs
src/ViewModels/Components/NativePlayerViewModel/NativePlayerViewModel.Methods.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Method.cs
src/ViewModels/Components/PlayerDetailViewModel/PlayerDetailViewModel.Video.cs
src/ViewModels/ViewModels.csproj
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/ViewModels/Views/SettingsPageViewModel/SettingsPageViewModel.cs

- close #423 - 解决处理备用流链接的问题
- close #422 - 本地环境复现，与 #423 原因一致
- close #424 - 由于需要修改处理备用流链接的逻辑，所以于此 PR 一同解决
- 同时修复了 HttpProvider.GetRequestMessageAsync 方法缺少 queryParams 参数时会引发空引用异常的问题（因为选择 URL 的逻辑需要修复这个问题）
- 修复了非 Visual Studio 的 IDE 和工具链会构建失败的问题，因为在我这不修这个问题编译都过不去...
这个 PR 的目的是什么？
- Bug 修复
- 功能
应用在 API 返回的 BaseUrl 不可用时不会切换到 BackupUrls，导致播放失败或无限加载，详见 #423 #422。
- 应用会在 BaseUrl 不可用时使用 BackupUrls 中可用的 Url 替换 BaseUrl。
- 当用户设置 “不使用 P2P 节点” 时将 BaseUrl 替换为 Host 不与正则表达式 `(mcdn.bilivideo.(cn|com)|szbdyd.com)` 不匹配的 Url。

为应用处理备用流链接和排除 P2P 节点的能力

---

src/Libs/Danmaku.Core/DanmakuRender.cs

弹幕同样使用 DX 渲染，但是画布没有做倍率缩放调整，导致在高分屏高缩放比例下存在肉眼可见的模糊。
修复方式时针对画布进行符合当前系统缩放比例的放大，然后在渲染时再等比缩小以适应视窗，这样就可以保证渲染效果清晰锐利。
这个 PR 的目的是什么？
- Bug 修复

修复弹幕在高缩放下的模糊问题

---

src/Desktop/BiliCopilot.UI/Controls/Player/DownloadButton.xaml
src/Desktop/BiliCopilot.UI/Controls/Player/DownloadButton.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerControlSettingControl.xaml
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DownloadViewModel/DownloadViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/SubtitleViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs

对于上传了字幕的视频，支持下载字幕。
AI 生成字幕不在此列
这个 PR 的目的是什么？
- 功能

支持字幕下载（不包括 AI 字幕）

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/ExternalPlayerViewModel/ExternalPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Events.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs

造成崩溃的主要原因：
1. 重复释放MPV播放器对象
2. 访问已释放对象的属性或方法
这个 PR 的目的是什么？
- Bug 修复

修复快速退出播放界面时的内存访问异常

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs

1. 播放区域内移动鼠标就会显示播放控制器
2. 将光标移入播放控制器范围内，控制器不会消失
3. 光标移出播放控制器区域后，播放控制器不会立刻消失，而是等待2秒后再消失
4. 去除对 PointerCaptureLost 的监听，对其监听后的处理会导致点击弹幕输入框时播放控制器消失
这个 PR 的目的是什么？
- Bug 修复
- 功能

优化播放控制器触发逻辑

---

src/Desktop/BiliCopilot.UI/ViewModels/Components/LiveChatSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.cs

窗口状态改变时触发滚动到底部的命令
这个 PR 的目的是什么？
- Bug 修复

修复退出播放独占后，直播消息列表没有滚动到底部的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Create.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.cs

修复在主窗口播放 WebDAV 时，如果按下空格键没有暂停的问题 
这个 PR 的目的是什么？
- Bug 修复
顺便去掉了弹幕的边距

修复 WebDAV 空格没有暂停的问题

---

src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlaylistSection.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerPlaylistSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoPlayerSeasonSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

现在点击播放列表/视频合集内的视频会优先在当前播放页面内加载
这个 PR 的目的是什么？
- Bug 修复

修复点击播放列表内的视频依然会在新窗口播放的问题

---

src/Desktop/BiliCopilot.UI/Controls/Components/EmoteTextBlock.xaml

修复评论弹出层被播放器遮挡的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.Win32.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/MpvPlayerViewModel/MpvPlayerViewModel.Overrides.cs

在播放完成后，播放器状态重置，因原先代码错误的判断条件，导致没有触发关闭逻辑。
这个 PR 的目的是什么？
- Bug 修复

修复岛播放器在退出后没有触发窗口关闭的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/Player/IslandPlayer.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PlayerPageViewModelBase.cs

如果在新窗口播放且在视频加载前切换窗口焦点就可能出现这个问题。所以在创建视图模型时就锁定窗口以避免这个情况发生
这个 PR 的目的是什么？
- Bug 修复

修复岛播放器初始化时的父窗口选择

---

src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Components/VideoFavoriteSectionDetailViewModel/VideoFavoriteSectionDetailViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/ViewLaterPageViewModel/ViewLaterPageViewModel.cs

如果默认播放模式是新窗口，则点击播放全部应当遵循这一设置
这个 PR 的目的是什么？
- Bug 修复

修复收藏夹/稍后再看的播放全部没有遵循播放行为偏好的问题

---

src/Desktop/BiliCopilot.UI/Controls/Player/FavoriteButton.xaml

将收藏菜单的位置调整到左侧，缓解全最大化时的窗口截断问题
这个 PR 的目的是什么？
- Bug 修复

调整收藏菜单的默认弹出位置以避免被截断

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/LiveDanmakuPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/Danmaku/LiveDanmakuPanel.xaml.cs
src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml
src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
src/Libs/Danmaku.Core/DanmakuFrostMaster.cs
src/Libs/Danmaku.Core/DanmakuRender.cs

不再使用 CanvasAnimatedControl 进行动画渲染，而是使用 CanvasSwapChainPanel 来进行更底层地控制，应用处理其生命周期，以保障渲染的稳定
这个 PR 的目的是什么？
- Bug 修复

修复弹幕重复渲染失败等问题

---

src/Desktop/BiliCopilot.UI/Controls/Danmaku/VideoDanmakuPanel.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/DanmakuViewModel/DanmakuViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs
src/Libs/Danmaku.Core/DanmakuFrostMaster.cs

过去使用分段加载，在频繁的进度跳转时很容易请求失败导致加载不出弹幕。
索性直接在视频加载时就把弹幕都加载好，也省得去计算当前分段了
这个 PR 的目的是什么？
- Bug 修复

载入视频时完全加载弹幕库

---

src/Desktop/BiliCopilot.UI.Models/Constants/SettingNames.cs
src/Desktop/BiliCopilot.UI/Controls/Settings/PlayerBehaviorSettingControl.xaml
src/Desktop/BiliCopilot.UI/Forms/PlayerWindow.xaml.cs
src/Desktop/BiliCopilot.UI/Resources/zh-Hans-CN/Resources.resw
src/Desktop/BiliCopilot.UI/ViewModels/Items/LiveItemViewModel/LiveItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.Properties.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SettingsPageViewModel/SettingsPageViewModel.cs

对于直播卡死，闪退的问题，由于我这边无法复现，所以只能取个折中的方案。
即仅在播放直播时使用网页播放器。
事实上哔哩助理本身提供的直播间功能非常有限，用网页反而是一种比较好的方式
这个 PR 的目的是什么？
- 功能

增加直播时使用网页播放器的选项

---

src/Desktop/BiliCopilot.UI/ViewModels/View/LivePlayerPageViewModel/LivePlayerPageViewModel.Operations.cs

在直播间内固定内容，会错误地把类型固定为视频，导致定向错误
这个 PR 的目的是什么？
- Bug 修复

修复直播间内固定内容的类型

---

src/Desktop/BiliCopilot.UI/Toolkits/IdToolkit.cs
src/Desktop/BiliCopilot.UI/ViewModels/Items/VideoItemViewModel/VideoItemViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/SearchPageViewModel/SearchPageViewModel.cs
src/Libs/Danmaku.Core/DanmakuFrostMaster.cs

在搜索框中输入AV号和BV号（BV必须大写），可以直接跳转到对应视频
这个 PR 的目的是什么？
- 功能

支持在搜索框中输入 AV/BV 号直接跳转到视频

---

src/Desktop/BiliCopilot.UI/Controls/Components/AppSearchBox.xaml
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.Methods.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/BiliPlayer.cs
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

二级标题栏对主标题栏造成了遮挡，影响了拖拽区域的计算
这个 PR 的目的是什么？
- Bug 修复
也修复了一个鼠标悬停引起MTC频繁切换显隐的问题

修复标题栏动画及搜索框聚焦问题

---

src/Desktop/BiliCopilot.UI/Controls/Player/VideoSeasonSection.xaml.cs

忘了更新选中项了
这个 PR 的目的是什么？
- Bug 修复

修复合集视频切换时无法重新选择初始视频的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/Core/IslandPlayerViewModel/IslandPlayerViewModel.Overrides.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Commands.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.Properties.cs

因为 MPV 发送的状态有点问题（少发状态），所以目前需要在视图模型中手动调整状态
这个 PR 的目的是什么？
- Bug 修复

修复非自动播放情况下的初始暂停状态

---

src/Desktop/BiliCopilot.UI/Controls/Player/VideoPlaylistSection.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.cs

修复播放列表内切换视频没有重载评论区的问题
这个 PR 的目的是什么？
- Bug 修复

修复在播放列表切换时没有重载选中项和评论区的问题

---

src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Methods.cs

加载新的视频时清除之前的侧边分区信息
这个 PR 的目的是什么？
- Bug 修复

修复切换视频后侧边分区内容没有刷新的问题

---

src/Desktop/BiliCopilot.UI/Controls/Core/TransportControl/VideoTransportControl.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/PlayerViewModelBase/PlayerViewModelBase.cs

将默认的快进步幅从 0.5 调整为 0.25，以支持 1.25 倍速
这个 PR 的目的是什么？
- 功能

将默认状态下的快进步幅调整为0.25

---

src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Directory.Packages.props

更新引用，去除标题栏运行平台标识

---

src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml
src/Desktop/BiliCopilot.UI/Controls/RootLayout.xaml.cs
src/Desktop/BiliCopilot.UI/ViewModels/Core/SubtitleViewModel.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/PgcPlayerPageViewModel/PgcPlayerPageViewModel.Operations.cs
src/Desktop/BiliCopilot.UI/ViewModels/View/VideoPlayerPageViewModel/VideoPlayerPageViewModel.Operations.cs

浅色模式下，全屏播放在左侧和顶部有白边，这个是 navigationView 没有正确切换 VisualState 导致的，手动切换一下即可
这个 PR 的目的是什么？

修复全屏状态下的播放器白边问题

---

src/Desktop/BiliCopilot.UI/BiliCopilot.UI.csproj
src/Desktop/BiliCopilot.UI/Controls/Core/Player/NativePlayer.cs
src/Desktop/BiliCopilot.UI/Controls/Core/Player/PlayerResources.xaml
src/Desktop/BiliCopilot.UI/Controls/Search/UserSectionDetailControl.xaml
src/Desktop/BiliCopilot.UI/ViewModels/Core/NativePlayerViewModel/NativePlayerViewModel.Overrides.cs

1. 搜索用户失败是因为引用了不存在的资源
2. 原生播放器崩溃原因很奇怪，加载资源时似乎并不能正确转换 MediaPlayerElement，解决方法是手动创建该控件
这个 PR 的目的是什么？
- Bug 修复

修复 AOT 遗留问题（搜索用户失败 / 原生播放器崩溃）
